// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "antevent": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/yinbaoqiang/goadame/design
// --out=$(GOPATH)/src/github.com/yinbaoqiang/goadame
// --version=v1.2.0-dirty

package client

import (
	"net/http"
)

// 创建事件成功返回 (default view)
//
// Identifier: application/vnd.ant.event.cre.result; view=default
type AntEventCreResult struct {
	// 事件唯一标识
	Eid *string `form:"eid,omitempty" json:"eid,omitempty" xml:"eid,omitempty"`
}

// DecodeAntEventCreResult decodes the AntEventCreResult instance encoded in resp body.
func (c *Client) DecodeAntEventCreResult(resp *http.Response) (*AntEventCreResult, error) {
	var decoded AntEventCreResult
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}
