// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "antevent": Application User Types
//
// Command:
// $ goagen
// --design=github.com/yinbaoqiang/goadame/design
// --out=E:\go\src\github.com\yinbaoqiang\goadame
// --version=v1.2.0-dirty

package client
