basePath: /v1
consumes:
- application/json
definitions:
  PostEventPayload:
    example:
      action: Quibusdam praesentium ullam.
      etype: Quia architecto.
      from: Soluta voluptatum neque possimus alias.
      occtime: Minima eum modi et corporis corporis.
      params: 0.6617215
    properties:
      action:
        description: 事件行为
        example: Quibusdam praesentium ullam.
        type: string
      etype:
        description: 事件类型
        example: Quia architecto.
        type: string
      from:
        description: 产生事件的服务器标识
        example: Soluta voluptatum neque possimus alias.
        type: string
      occtime:
        description: 事件发生时间
        example: Minima eum modi et corporis corporis.
        type: string
      params:
        description: 事件发生时间
        example: 0.6617215
    required:
    - etype
    - action
    - from
    title: PostEventPayload
    type: object
  PutEventPayload:
    example:
      action: Consequatur vitae ut.
      eid: Natus ut quidem pariatur voluptatem perferendis corrupti.
      etype: Quia quisquam in.
      from: Quia aut non eius perspiciatis consequuntur.
      occtime: Voluptatem quibusdam dolores et excepturi.
      params: 7.9144667e+18
    properties:
      action:
        description: 事件行为
        example: Consequatur vitae ut.
        type: string
      eid:
        description: 事件唯一标识
        example: Natus ut quidem pariatur voluptatem perferendis corrupti.
        type: string
      etype:
        description: 事件类型
        example: Quia quisquam in.
        type: string
      from:
        description: 产生事件的服务器标识
        example: Quia aut non eius perspiciatis consequuntur.
        type: string
      occtime:
        description: 事件发生时间
        example: Voluptatem quibusdam dolores et excepturi.
        type: string
      params:
        description: 事件发生时间
        example: 7.9144667e+18
    required:
    - eid
    - etype
    - action
    - from
    title: PutEventPayload
    type: object
host: localhost:8080
info:
  description: 这是一个事件服务引擎
  title: 蚁动事件引擎
  version: ""
paths:
  /event:
    post:
      description: 创建一个事件
      operationId: event#post
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/PostEventPayload'
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: post event
      tags:
      - event
    put:
      description: 创建一个事件
      operationId: event#put
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/PutEventPayload'
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      schemes:
      - http
      summary: put event
      tags:
      - event
produces:
- application/json
schemes:
- http
swagger: "2.0"
