basePath: /v1
consumes:
- application/json
definitions:
  AddRegeventPayload:
    example:
      action: Quam fugiat aliquid repudiandae.
      bakurl: Recusandae repellendus rerum dolorem libero sunt.
      etype: Nemo sit aut neque.
      from: Minus omnis aliquid optio.
    properties:
      action:
        description: 事件行为,不设置该项则注册监听所有行为变化
        example: Quam fugiat aliquid repudiandae.
        type: string
      bakurl:
        description: 回调路径
        example: Recusandae repellendus rerum dolorem libero sunt.
        type: string
      etype:
        description: 事件类型
        example: Nemo sit aut neque.
        type: string
      from:
        description: 产生事件的服务器标识
        example: Minus omnis aliquid optio.
        type: string
    required:
    - etype
    - bakurl
    - from
    title: AddRegeventPayload
    type: object
  AntReg:
    description: 事件监听信息 (default view)
    example:
      action: Quibusdam praesentium ullam.
      bakurl: Quia architecto.
      etype: Soluta voluptatum neque possimus alias.
      from: Minima eum modi et corporis corporis.
      rid: Reprehenderit asperiores consequatur vitae ut.
    properties:
      action:
        description: 事件行为,不设置该项则注册监听所有行为变化
        example: Quibusdam praesentium ullam.
        type: string
      bakurl:
        description: 回调路径
        example: Quia architecto.
        type: string
      etype:
        description: 事件类型
        example: Soluta voluptatum neque possimus alias.
        type: string
      from:
        description: 产生事件的服务器标识
        example: Minima eum modi et corporis corporis.
        type: string
      rid:
        description: 注册事件监听唯一标识
        example: Reprehenderit asperiores consequatur vitae ut.
        type: string
    required:
    - rid
    - etype
    - bakurl
    - from
    title: 'Mediatype identifier: application/vnd.ant.reg+json; view=default'
    type: object
  AntRegList:
    description: 事件监听列表 (default view)
    example:
      list:
      - action: Quibusdam praesentium ullam.
        bakurl: Quia architecto.
        etype: Soluta voluptatum neque possimus alias.
        from: Minima eum modi et corporis corporis.
        rid: Reprehenderit asperiores consequatur vitae ut.
      - action: Quibusdam praesentium ullam.
        bakurl: Quia architecto.
        etype: Soluta voluptatum neque possimus alias.
        from: Minima eum modi et corporis corporis.
        rid: Reprehenderit asperiores consequatur vitae ut.
      total: 8.520824e+17
    properties:
      list:
        description: 事件类型
        example:
        - action: Quibusdam praesentium ullam.
          bakurl: Quia architecto.
          etype: Soluta voluptatum neque possimus alias.
          from: Minima eum modi et corporis corporis.
          rid: Reprehenderit asperiores consequatur vitae ut.
        - action: Quibusdam praesentium ullam.
          bakurl: Quia architecto.
          etype: Soluta voluptatum neque possimus alias.
          from: Minima eum modi et corporis corporis.
          rid: Reprehenderit asperiores consequatur vitae ut.
        items:
          $ref: '#/definitions/AntReg'
        type: array
      total:
        description: 总数量
        example: 8.520824e+17
        format: int64
        type: integer
    required:
    - total
    title: 'Mediatype identifier: application/vnd.ant.reg.list+json; view=default'
    type: object
  AntRegResult:
    description: 注册事件监听成功 (default view)
    example:
      ok: true
    properties:
      ok:
        description: 成功标识
        example: true
        type: boolean
    title: 'Mediatype identifier: application/vnd.ant.reg.result+json; view=default'
    type: object
  AntResult:
    description: 创建事件成功返回 (default view)
    example:
      eid: Quod quia aut non eius.
    properties:
      eid:
        description: 事件唯一标识
        example: Quod quia aut non eius.
        type: string
    title: 'Mediatype identifier: application/vnd.ant.result+json; view=default'
    type: object
  PostEventPayload:
    example:
      action: Consequuntur voluptas.
      etype: Quibusdam dolores et excepturi asperiores porro ipsum.
      from: Facere aspernatur natus modi quia.
      occtime: Tenetur corporis sequi illo dolor deserunt ipsam.
      params: true
    properties:
      action:
        description: 事件行为
        example: Consequuntur voluptas.
        type: string
      etype:
        description: 事件类型
        example: Quibusdam dolores et excepturi asperiores porro ipsum.
        type: string
      from:
        description: 产生事件的服务器标识
        example: Facere aspernatur natus modi quia.
        type: string
      occtime:
        description: 事件发生时间
        example: Tenetur corporis sequi illo dolor deserunt ipsam.
        type: string
      params:
        description: 事件发生时间
        example: true
    required:
    - etype
    - action
    - from
    title: PostEventPayload
    type: object
  PutEventPayload:
    example:
      action: Qui fugit rerum ab itaque.
      etype: Sit eius ad voluptas suscipit sed.
      from: Laudantium illo non.
      occtime: Earum et quia quia cum voluptate.
      params: 1332dacb-ae10-4960-a446-41f85d722f0e
    properties:
      action:
        description: 事件行为
        example: Qui fugit rerum ab itaque.
        type: string
      etype:
        description: 事件类型
        example: Sit eius ad voluptas suscipit sed.
        type: string
      from:
        description: 产生事件的服务器标识
        example: Laudantium illo non.
        type: string
      occtime:
        description: 事件发生时间
        example: Earum et quia quia cum voluptate.
        type: string
      params:
        description: 事件发生时间
        example: 1332dacb-ae10-4960-a446-41f85d722f0e
    required:
    - etype
    - action
    - from
    title: PutEventPayload
    type: object
host: localhost:8080
info:
  description: 这是一个事件服务引擎
  title: 蚁动事件引擎
  version: ""
paths:
  /admin/event:
    get:
      description: 注册事件监听
      operationId: regevent#list
      parameters:
      - description: 事件行为,不设置该项则注册监听所有行为变化
        in: query
        name: count
        required: false
        type: integer
      - description: 事件类型
        in: query
        name: page
        required: false
        type: integer
      produces:
      - application/vnd.ant.reg.list+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AntRegList'
      schemes:
      - http
      summary: list regevent
      tags:
      - regevent
  /admin/event/{rid}:
    delete:
      description: 取消事件监听
      operationId: regevent#remove
      parameters:
      - description: 事件监听唯一标识
        in: path
        name: rid
        required: true
        type: string
      produces:
      - application/vnd.ant.result+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AntResult'
      schemes:
      - http
      summary: remove regevent
      tags:
      - regevent
  /admin/event/reg:
    post:
      description: 注册事件监听
      operationId: regevent#add
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/AddRegeventPayload'
      produces:
      - application/vnd.ant.reg.result+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AntRegResult'
      schemes:
      - http
      summary: add regevent
      tags:
      - regevent
  /event:
    post:
      description: 创建一个事件
      operationId: event#post
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/PostEventPayload'
      produces:
      - application/vnd.ant.result+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AntResult'
      schemes:
      - http
      summary: post event
      tags:
      - event
  /event/{eid}:
    put:
      description: 创建一个事件
      operationId: event#put
      parameters:
      - description: 事件唯一标识
        in: path
        name: eid
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/PutEventPayload'
      produces:
      - application/vnd.ant.result+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AntResult'
        "404":
          description: Not Found
      schemes:
      - http
      summary: put event
      tags:
      - event
produces:
- application/json
responses:
  NotFound:
    description: Not Found
schemes:
- http
swagger: "2.0"
