basePath: /v1
consumes:
- application/json
definitions:
  AntEventCreResult:
    description: 创建事件成功返回 (default view)
    example:
      eid: At architecto consectetur voluptas quod ut id.
    properties:
      eid:
        description: 事件唯一标识
        example: At architecto consectetur voluptas quod ut id.
        type: string
    title: 'Mediatype identifier: application/vnd.ant.event.cre.result+json; view=default'
    type: object
  PostEventPayload:
    example:
      action: Quibusdam praesentium ullam.
      etype: Quia architecto.
      from: Soluta voluptatum neque possimus alias.
      occtime: Minima eum modi et corporis corporis.
      params: 0.6617215
    properties:
      action:
        description: 事件行为
        example: Quibusdam praesentium ullam.
        type: string
      etype:
        description: 事件类型
        example: Quia architecto.
        type: string
      from:
        description: 产生事件的服务器标识
        example: Soluta voluptatum neque possimus alias.
        type: string
      occtime:
        description: 事件发生时间
        example: Minima eum modi et corporis corporis.
        type: string
      params:
        description: 事件发生时间
        example: 0.6617215
    required:
    - etype
    - action
    - from
    title: PostEventPayload
    type: object
  PutEventPayload:
    example:
      action: Consequatur vitae ut.
      etype: Natus ut quidem pariatur voluptatem perferendis corrupti.
      from: Quia quisquam in.
      occtime: Quia aut non eius perspiciatis consequuntur.
      params: false
    properties:
      action:
        description: 事件行为
        example: Consequatur vitae ut.
        type: string
      etype:
        description: 事件类型
        example: Natus ut quidem pariatur voluptatem perferendis corrupti.
        type: string
      from:
        description: 产生事件的服务器标识
        example: Quia quisquam in.
        type: string
      occtime:
        description: 事件发生时间
        example: Quia aut non eius perspiciatis consequuntur.
        type: string
      params:
        description: 事件发生时间
        example: false
    required:
    - etype
    - action
    - from
    title: PutEventPayload
    type: object
host: localhost:8080
info:
  description: 这是一个事件服务引擎
  title: 蚁动事件引擎
  version: ""
paths:
  /event:
    post:
      description: 创建一个事件
      operationId: event#post
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/PostEventPayload'
      produces:
      - application/vnd.ant.event.cre.result+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AntEventCreResult'
      schemes:
      - http
      summary: post event
      tags:
      - event
  /event/{eid}:
    put:
      description: 创建一个事件
      operationId: event#put
      parameters:
      - description: 事件唯一标识
        in: path
        name: eid
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/PutEventPayload'
      produces:
      - application/vnd.ant.event.cre.result+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AntEventCreResult'
        "404":
          description: Not Found
      schemes:
      - http
      summary: put event
      tags:
      - event
produces:
- application/json
responses:
  NotFound:
    description: Not Found
schemes:
- http
swagger: "2.0"
