// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "antevent": CLI Commands
//
// Command:
// $ goagen
// --design=github.com/yinbaoqiang/goadame/design
// --out=$(GOPATH)/src/github.com/yinbaoqiang/goadame
// --version=v1.2.0-dirty

package cli

import (
	"context"
	"encoding/json"
	"github.com/goadesign/goa"
	goaclient "github.com/goadesign/goa/client"
	uuid "github.com/goadesign/goa/uuid"
	"github.com/spf13/cobra"
	"github.com/yinbaoqiang/goadame/client"
	"log"
	"os"
	"strconv"
	"strings"
	"time"
)

type (
	// CreateEventCommand is the command line data structure for the create action of event
	CreateEventCommand struct {
		// 事件行为
		Action string
		// 事件唯一标识
		Eid string
		// 事件类型
		Etype string
		// 产生事件的服务器标识
		From string
		// 事件发生时间
		Occtime string
		// 事件发生时间
		Params      string
		PrettyPrint bool
	}

	// Create2EventCommand is the command line data structure for the create2 action of event
	Create2EventCommand struct {
		// 事件行为
		Action string
		// 事件类型
		Etype string
		// 产生事件的服务器标识
		From string
		// 事件发生时间
		Occtime string
		// 事件发生时间
		Params      string
		PrettyPrint bool
	}
)

// RegisterCommands registers the resource action CLI commands.
func RegisterCommands(app *cobra.Command, c *client.Client) {
	var command, sub *cobra.Command
	command = &cobra.Command{
		Use:   "create",
		Short: `创建一个事件`,
	}
	tmp1 := new(CreateEventCommand)
	sub = &cobra.Command{
		Use:   `event ["/v1/event"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp1.Run(c, args) },
	}
	tmp1.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp1.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "create2",
		Short: `创建一个事件`,
	}
	tmp2 := new(Create2EventCommand)
	sub = &cobra.Command{
		Use:   `event ["/v1/event"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp2.Run(c, args) },
	}
	tmp2.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp2.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
}

func intFlagVal(name string, parsed int) *int {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func float64FlagVal(name string, parsed float64) *float64 {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func boolFlagVal(name string, parsed bool) *bool {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func stringFlagVal(name string, parsed string) *string {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func hasFlag(name string) bool {
	for _, arg := range os.Args[1:] {
		if strings.HasPrefix(arg, "--"+name) {
			return true
		}
	}
	return false
}

func jsonVal(val string) (*interface{}, error) {
	var t interface{}
	err := json.Unmarshal([]byte(val), &t)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func jsonArray(ins []string) ([]interface{}, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []interface{}
	for _, id := range ins {
		val, err := jsonVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, val)
	}
	return vals, nil
}

func timeVal(val string) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339, val)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func timeArray(ins []string) ([]time.Time, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []time.Time
	for _, id := range ins {
		val, err := timeVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

func uuidVal(val string) (*uuid.UUID, error) {
	t, err := uuid.FromString(val)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func uuidArray(ins []string) ([]uuid.UUID, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []uuid.UUID
	for _, id := range ins {
		val, err := uuidVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

func float64Val(val string) (*float64, error) {
	t, err := strconv.ParseFloat(val, 64)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func float64Array(ins []string) ([]float64, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []float64
	for _, id := range ins {
		val, err := float64Val(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

func boolVal(val string) (*bool, error) {
	t, err := strconv.ParseBool(val)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func boolArray(ins []string) ([]bool, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []bool
	for _, id := range ins {
		val, err := boolVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

// Run makes the HTTP request corresponding to the CreateEventCommand command.
func (cmd *CreateEventCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/v1/event"
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	var tmp3 *interface{}
	if cmd.Params != "" {
		var err error
		tmp3, err = jsonVal(cmd.Params)
		if err != nil {
			goa.LogError(ctx, "failed to parse flag into *interface{} value", "flag", "--params", "err", err)
			return err
		}
	}
	resp, err := c.CreateEvent(ctx, path, stringFlagVal("action", cmd.Action), stringFlagVal("eid", cmd.Eid), stringFlagVal("etype", cmd.Etype), stringFlagVal("from", cmd.From), stringFlagVal("occtime", cmd.Occtime), tmp3)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *CreateEventCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var action string
	cc.Flags().StringVar(&cmd.Action, "action", action, `事件行为`)
	var eid string
	cc.Flags().StringVar(&cmd.Eid, "eid", eid, `事件唯一标识`)
	var etype string
	cc.Flags().StringVar(&cmd.Etype, "etype", etype, `事件类型`)
	var from string
	cc.Flags().StringVar(&cmd.From, "from", from, `产生事件的服务器标识`)
	var occtime string
	cc.Flags().StringVar(&cmd.Occtime, "occtime", occtime, `事件发生时间`)
	var params string
	cc.Flags().StringVar(&cmd.Params, "params", params, `事件发生时间`)
}

// Run makes the HTTP request corresponding to the Create2EventCommand command.
func (cmd *Create2EventCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/v1/event"
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	var tmp4 *interface{}
	if cmd.Params != "" {
		var err error
		tmp4, err = jsonVal(cmd.Params)
		if err != nil {
			goa.LogError(ctx, "failed to parse flag into *interface{} value", "flag", "--params", "err", err)
			return err
		}
	}
	resp, err := c.Create2Event(ctx, path, stringFlagVal("action", cmd.Action), stringFlagVal("etype", cmd.Etype), stringFlagVal("from", cmd.From), stringFlagVal("occtime", cmd.Occtime), tmp4)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *Create2EventCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var action string
	cc.Flags().StringVar(&cmd.Action, "action", action, `事件行为`)
	var etype string
	cc.Flags().StringVar(&cmd.Etype, "etype", etype, `事件类型`)
	var from string
	cc.Flags().StringVar(&cmd.From, "from", from, `产生事件的服务器标识`)
	var occtime string
	cc.Flags().StringVar(&cmd.Occtime, "occtime", occtime, `事件发生时间`)
	var params string
	cc.Flags().StringVar(&cmd.Params, "params", params, `事件发生时间`)
}
